### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by chrisflesher** [rcvfortexas/rcvfortexas#32]
From Harriet: Our October 5 meeting is listed under events but is there an easy way to make the invitation the landing page for our website from now until that date?

**Comment by DJ-Eckam** [comment]
I think instead of just making the invitation the main landing page, it makes more sense to add a prominent link to the home page. I've done that. I put it below the "Why" section. Would've liked to put it above that but that is the page headline which is set separately from the content so I couldn't figure out how to do that.

Let me know what you think of how it is now.

**Comment by DJ-Eckam** [comment]
Okay, on 2nd thought, I figured out how to make it better, putting this info at the top -- just make the headline the new message headline. (Still getting used to NB.)
