### ISSUE TITLE
Rankit polls

### ISSUE THREAD

**Issue by chrisflesher** [rcvfortexas/rcvfortexas#38]
From Harriet: At the statewide meeting, someone from Austin suggested housing a bunch of Rankit polls on a website so people can respond to whichever they find of interest and see how RCV votes. I could see that as a separate bullet under About RCV.

**Comment by ironunicorn** [comment]
@DJ-Eckam @hwasserstrum would you people be the right ones to ask about this?

I'm thinking of just hosting a rankit.vote poll in an iframe (meaning just put a box on one of our webpages that displays the rankit.vote poll page). Does that sound good? If so, which page would be best to do this (maybe here: [https://www.rcvfortexas.org/what_is_rcv_1](https://www.rcvfortexas.org/what_is_rcv_1))?  Also, what should the poll be about?

**Comment by DJ-Eckam** [comment]
Sorry, I thought I had assigned this to myself. I contacted NB support about it and just saw their response. Will need a custom page template which is no big deal. My understanding from Harriet was that this should be a separate page so I have created a test page with the slug /rankit_polls. I will have it working as a test soon.

**Comment by DJ-Eckam** [comment]
@ironunicorn I'll be happy to hand this off to you if you want to work on it. I just sent a follow-up question to NB about how to combine a custom template w. the "Content" tab and will update when I hear back from them.

**Comment by ironunicorn** [comment]
Oh no! This ticket was just mentioned in the technology meeting and I volunteered. It sounds like you have a handle on it so I'll defer to you.

**Comment by hwasserstrum** [comment]
There is a favorite apple pie survey going on now on our social media for Thanksgiving and there will be one on favorite cookie for National Cookie Day coming up shortly thereafter. See below.

| 
Nov 24  Wednesday: Fatima:
 |
| 
Post 1 Headline: Thanksgiving Poll Time

Body copy: What’s your favorite Pie? Click on the link to vote using Ranked Choice Voting! See how RCV works in real time. 

Image:

URL: https://rankit.vote/vote/BQT1rJWfqJpTN82NLsLE



#tag: #RCV #RankedChoiceVoting #Pie #Thanksgiving #Poll #RCVforTX



 |



| 
Dec 4  Saturday: Richard: National Cookie Day - Poll for favorite type of cookie - Demonstrate RCV
 |
| 
Post 1 Headline: National Cookie Day!

Body copy: Today is National Cookie Day! We gotta know…. What’s the best Cookie? Click on the link to vote using Ranked Choice Voting! See how RCV works in real time. 

Image: (2 options)



URL: https://rankit.vote/vote/QmUGR0Jug7mIHIEXbJbJ


#tag: #RCV #RCVforTX #Cookies #CookiePoll #PollInAction #Election #Vote #VotingRights #FairVote #MoreChoices #PeopleVote #YourVoteMatters


 |


    On Sunday, November 21, 2021, 02:45:09 PM CST, Irene Foelschow ***@***.***> wrote:  
 
 


@DJ-Eckam @hwasserstrum would you people be the right ones to ask about this?

I'm thinking of just hosting a rankit.vote poll in an iframe (meaning just put a box on one of our webpages that displays the rankit.vote poll page). Does that sound good? If so, which page would be best to do this (maybe here: https://www.rcvfortexas.org/what_is_rcv_1)? Also, what should the poll be about?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chrisflesher** [comment]
I tried using the RankIt tool but could not access any of the polls listed on the RCV website once logged in.

**Comment by hwasserstrum** [comment]
I have been told that the only tool that can be used on a website is from rankedvote.com which costs $60/month. I don't know if that is true. Dan has been trying to add polls to our website and might have further insight to add.Harriet
    On Monday, December 20, 2021, 08:07:05 AM CST, chrisflesher ***@***.***> wrote:  
 
 


I tried using the RankIt tool but could not access any of the polls listed on the RCV website once logged in.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DJ-Eckam** [comment]
I've seen Rankit be unavailable in the past so maybe it is not so stable. The links on our What Is RCV? page all work for me, once I'm logged in. Is it possible they were having a "glitch" when Chris tried it? 

I think Rankit basically works, it's just not the greatest user experience, especially in its embedded form which we've opted not to use, in favor of links.

**Comment by chrisflesher** [comment]
I tried the link again and am not seeing any polls. Can anyone else see them? Or am I just getting unlucky?

**Comment by DJ-Eckam** [comment]
I think I've managed to get attention to the issue by tweeting at Fairvote -- we exchanged messages and I'm hopeful they will address the problem soon.

**Comment by DJ-Eckam** [comment]
okay I believe this problem is fixed now. I was using the wrong URLs for voting -- d'ohh!

**Comment by hwasserstrum** [comment]
Thanks! Looks good.
    On Friday, January 28, 2022, 01:02:28 PM CST, DJ-Eckam ***@***.***> wrote:  
 
 


Closed #38.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
