### ISSUE TITLE
Automate RSVP reminder e-mail

### ISSUE THREAD

**Issue by chrisflesher** [rcvfortexas/rcvfortexas#58]
Investigate if it is possible to send a reminder e-mail to people who have RSVP'd for an event. If possible automatically send them a reminder the day before. (requested by Brian Dorfman, the Social Outreach lead)

Some relevant info:
https://support.nationbuilder.com/en/articles/2363242-events-creation-to-completion#step-2-email-RSVPs
https://support.nationbuilder.com/en/articles/3497865-workflows-and-automations

**Comment by DJ-Eckam** [comment]
Looks like NB's way to do this is to schedule an email blast using a filter defined as "has rsvp'ed to" a selected event. This page explains: https://support.nationbuilder.com/en/articles/2363242-events-creation-to-completion#step-2-email-RSVPs

- but it's a little out of date - instead of clicking "Filter", click on the Y-shaped icon (representing filtering)... and in the Add Criteria menu, look under Activity instead of Event.

**Comment by DJ-Eckam** [comment]
Sorry, just noticed that URL is a duplicate of what Chris posted.

I guess the question is, can whoever creates the event also handle these steps? Or should it be someone else's responsibility?

**Comment by chrisflesher** [comment]
Put the instructions for this in this doc:
https://docs.google.com/document/d/1HRaqPZ05-ZM_GwuecKIIUkyE5mFZZ7Vsz66EPxCv14A/edit
